name: "Verify Windows ARM64 Native"

on:
  workflow_dispatch:
  push:
    branches:
      - verify-windows-arm64-native-test

jobs:
  prep:
    uses: ./.github/workflows/prep.yml

  windows-arm64-native:
    needs: prep
    runs-on: windows-11-arm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: "Generic Setup"
        uses: ./.github/actions/build-setup
      - name: "Setup build variables"
        shell: bash
        run: |
          echo "TECTONIC_DEP_BACKEND=vcpkg" >> "$GITHUB_ENV"
          echo "VCPKG_ROOT=$GITHUB_WORKSPACE/target/vcpkg" >> "$GITHUB_ENV"
          echo "RUSTFLAGS=-Ctarget-feature=+crt-static" >> "$GITHUB_ENV"
          echo "VCPKGRS_TRIPLET=arm64-windows-static-release" >> "$GITHUB_ENV"
          echo "VCPKG_DEFAULT_HOST_TRIPLET=arm64-windows-static-release" >> "$GITHUB_ENV"
          echo "RUST_TEST_THREADS=1" >> "$GITHUB_ENV"
      - name: "Install vcpkg dependencies"
        uses: ./.github/actions/vcpkg-deps
        with:
          target: aarch64-pc-windows-msvc
      - name: "Build and Test"
        uses: ./.github/actions/build-and-test
        with:
          target: aarch64-pc-windows-msvc
          publish: false
